name: fude-software-back
services:
  database:
    image: postgres:18
    container_name: log_relay-pg
    networks:
      - fude_bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: log_relay
      POSTGRES_USER: log_relay
      POSTGRES_PASSWORD: devpass
    volumes:
      - /mnt/drive1/postgres_data:/var/lib/postgresql/data
  log_relay:
    image: golang:1.26
    container_name: log_relay-svc
    working_dir: /app
    depends_on: 
      - database
    networks:
      - fude_bridge
    ports:
      - "30000:30000"
    env_file:
      - .env
    volumes:
      - type: bind
        source: "${GOMODCACHE:-$HOME/go/pkg/mod}"
        target: /go/pkg/mod
      - type: bind
        source: .
        target: /app
    command: /app/build_and_run.sh

networks:
  fude_bridge: {}

