name: fude-software-back-staging

services:
  database:
    image: postgres:18
    container_name: log_relay-pg-staging

    environment:
      POSTGRES_DB: log_relay
      POSTGRES_USER: log_relay
      POSTGRES_PASSWORD: devpass

    volumes:
        - /mnt/drive1/postgres_data_test:/var/lib/postgresql

    networks:
      - fude_bridge

    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U log_relay"]
      interval: 5s
      timeout: 5s
      retries: 10


  log_relay:
    build: .

    container_name: log_relay-svc-staging

    depends_on:
      database:
        condition: service_healthy

    networks:
      - fude_bridge

    ports:
      - "30001:30000"

    env_file:
      - .env

    restart: unless-stopped


networks:
  fude_bridge:
    driver: bridge